### ISSUE TITLE
Holy COW you are fast! Mind if I contribute?

### ISSUE THREAD

**Issue by ErichDonGubler** [nabijaczleweli/registry.pol-rs#2]
I've actually been working on the problem this crate solves, and was hoping I could contribute some of the work I'd done. I did this way before I ever posted on the Not-Yet-Awesome Rust list, because it wasn't complete -- I had no idea somebody would try to actually implement a seemingly obscure Windows thing! Kudos to you!

https://gitlab.com/erichdongubler/windows-registry-rs

I'm filing this as an issue first to ask if you're interested at all in receiving PRs or taking on another maintainer for this crate. I hadn't written a `nom` parser yet for everything, but I do have code, tests, and some domain expertise I could contribute. What do you think?

**Comment by nabijaczleweli** [comment]
I am always interested in getting PRs! Just keep in mind the relatively smaller scope, and that any Windows-specific libraries are *verboten*. (Actually, I should add that to top-level doc.)

**Comment by ErichDonGubler** [comment]
Yeah, that was one of my goals later for what I had been writing -- being able to parse these files anywhere is not made unreasonable just by inlining a few constants! It's easy enough to set up a Windows-only test against `winapi`'s constants in a test module.

**Comment by nabijaczleweli** [comment]
and that's another great idea
